version: 1.0.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: DatToXLS.sln
  verbosity: minimal
after_build:
- cmd: '"packages\NSIS.2.51\tools\makensis.exe" "installer\DatToXLS.nsi"'
deploy:
- provider: GitHub
  auth_token:
    secure: gX7uENpEovQdzscLdFEkic6eRFdekgL5T9Uuo/XIGwq7PSTFqnrka1xi+FTDDnYv
  prerelease: true