version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  EnableNuGetPackageRestore: ON
build:
  project: DatToXLS.sln
  verbosity: minimal
after_build:
- cmd: '"packages\NSIS.2.51\tools\makensis.exe" "installer\KeepAwake.nsi"'
deploy:
- provider: GitHub
  auth_token:
    secure: gX7uENpEovQdzscLdFEkic6eRFdekgL5T9Uuo/XIGwq7PSTFqnrka1xi+FTDDnYv
  prerelease: true